version: '3'

services:
  mysql:
    container_name: 'mysql_api_base'
    image: mysql:8.0.23
    restart: always
    environment:
      MYSQL_DATABASE: 'api-base'
      MYSQL_USER: 'api-base-user'
      MYSQL_PASSWORD: 'api-base-password'
      MYSQL_ROOT_PASSWORD: 'api-base-password'
    ports:
      - '3301:3306'
    expose:
      - '3301'
  postgre:
    container_name: 'postgres-api-base'
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: api-base-password
      POSTGRES_USER: api-base-user
      POSTGRES_DB: api-base
    ports:
      - '3302:5432'
    expose:
      - '3302'
  mongo:
    image: mongo:4.2
    container_name: mongo_api-base
    ports:
      - '3303:27017'
    expose:
      - '3303'
    environment:
      MONGO_INITDB_DATABASE: api-base
      MONGO_INITDB_ROOT_USERNAME: api-base-user
      MONGO_INITDB_ROOT_PASSWORD: api-base-password
